### ISSUE TITLE
no module named aiohttp, but installed aiohttp==3.8.1

### ISSUE THREAD

**Issue by oasn** [charliebrassington/one#1]
![Bild_2023-09-02_164100709](https://github.com/charliebrassington/one/assets/120338660/b2c2660d-f3ea-4751-9288-bacfd9bcea71)
i already runned "pip install -r requirements.txt" and it still shows me "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
search-engine-parser 0.6.3 requires aiohttp==3.8.1, but you have aiohttp 3.8.5 which is incompatible." i already tried to manually install aiohttp==3.8.1 and it still don't recognized it. what's wrong here?

best regards

**Comment by charliebrassington** [comment]
When you do "pip show aiohttp" It displays the location as "python38" which is Python 3.8 but when you run the main.py you're using python 3.9. You could try using "pip3.9" or "pip3" one should work. This situation occurs when you have multiple python versions. If using "pip3.9" or "pip3" doesn't work you can always try adding -m to the python command and running the pip install from there. If you need any more help let me know
